version: '3.8'

networks:
  monitoring:
    driver: bridge
services:
  prometeus:
    hostname: prometheus
    image: prom/prometheus:v2.20.1
    container_name: prometheus
    volumes:
      - ./prometheus:/etc/prometheus
      - prometheus_data:/prometheus
    ports:
      - 8081:9090
    expose:
      - 9090
    networks:
      - monitoring
  grafana:
    image: grafana/grafana:11.4.0
    depends_on:
      - prometeus
      - otel-collector
    container_name: grafana
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/dashboards:/var/lib/grafana/dashboards
    environment:
      - GF_AUTH_DISABLE_LOGIN_FORM=true
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_DASHBOARDS_DEFAULT_HOME_DASHBOARD_PATH=/var/lib/grafana/dashboards/dashboard.json
    ports:
      - 8082:3000
    expose:
      - 3000
    networks:
      - monitoring
  
  tempo:
    image: grafana/tempo:2.6.1
    container_name: tempo
    ports:
      - 3200:3200
    expose:
      - 3200
    networks:
      - monitoring
    volumes:
      - tempo_data:/tmp/tempo
      - ./grafana-tempo/tempo-config.yaml:/etc/tempo-config.yaml
    command:
      - -config.file=/etc/tempo-config.yaml


  loki: 
    image: grafana/loki:3.0.0
    ports: 
      - 3100:3100
    networks:
      - monitoring
    volumes:
      - ./loki/loki-config.yaml:/etc/loki/local-config.yaml
    command: -config.file=/etc/loki/local-config.yaml
    expose:
      - 3100

  promtail:
    image: grafana/promtail:latest
    networks:
      - monitoring
    volumes:
      - /var/log/recipes-app:/var/log/recipes-app
      - ./promtail/promtail-config.yaml:/etc/promtail/promtail-config.yaml
    command: -config.file=/etc/promtail/promtail-config.yaml
  
  otel-collector:
    image: otel/opentelemetry-collector:latest
    depends_on:
      - tempo
    volumes:
      - ./open-telemetry/otel-collector-config.yaml:/etc/otel-collector-config.yaml
    command:
      - --config=/etc/otel-collector-config.yaml
    ports:
      - 4317:4317
      - 4318:4318
    expose:
      - 4317
      - 4318
    networks:
      - monitoring

  # jaeger:
  #   image: jaegertracing/all-in-one:latest
  #   ports:
  #     - 6831:6831/udp
  #     - 6832:6832/udp
  #     - 5778:5778
  #     - 16686:16686
  #     - 14250:14250
  #     - 14268:14268
  #     - 14269:14269
  #     - 9411:9411
  #   networks:
  #     - monitoring

  recipes-app:
    hostname: recipes-app
    build:
      context: ./
    ports:
      - 8080:8080
    expose:
      - 8080
    networks:
      - monitoring
volumes:
    prometheus_data: {}
    grafana_data: {}
    tempo_data: {}