version: '3.8'

networks:
  monitoring:
    driver: bridge
services:
  prometeus:
    hostname: prometheus
    image: prom/prometheus:v2.20.1
    container_name: prometheus
    volumes:
      - ./prometheus:/etc/prometheus
      - prometheus_data:/prometheus
    ports:
      - 8081:9090
    expose:
      - 9090
    networks:
      - monitoring
  grafana:
    image: grafana/grafana:7.1.5
    depends_on:
      - prometeus
    container_name: grafana
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/dashboards:/var/lib/grafana/dashboards
    environment:
      - GF_AUTH_DISABLE_LOGIN_FORM=true
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_DASHBOARDS_DEFAULT_HOME_DASHBOARD_PATH=/var/lib/grafana/dashboards/dashboard.json
    ports:
      - 8082:3000
    expose:
      - 3000
    networks:
      - monitoring
  
  loki: 
    image: grafana/loki:3.0.0
    ports: 
      - 3100:3100
    networks:
      - monitoring
    volumes:
      - ./loki/loki-config.yaml:/etc/loki/local-config.yaml
    command: -config.file=/etc/loki/local-config.yaml
    expose:
      - 3100

  promtail:
    image: grafana/promtail:latest
    networks:
      - monitoring
    volumes:
      - /var/log/recipes-app:/var/log/recipes-app
      - ./promtail/promtail-config.yaml:/etc/promtail/promtail-config.yaml
    command: -config.file=/etc/promtail/promtail-config.yaml
  
  recipes-app:
    hostname: recipes-app
    build:
      context: ./
    ports:
      - 8080:8080
    expose:
      - 8080
    networks:
      - monitoring
volumes:
    prometheus_data: {}
    grafana_data: {}