version: '3.8'

networks:
  monitoring:
    driver: bridge
services:
  prometeus:
    hostname: prometeus
    image: prom/prometheus:v2.20.1
    container_name: prometheus
    volumes:
      - ./prometheus:/etc/prometheus
      - prometheus_data:/prometheus
    ports:
      - 8081:9090
    expose:
      - 9090
    networks:
      - monitoring
  grafana:
    image: grafana/grafana:7.1.5
    container_name: grafana
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
    environment:
      - GF_AUTH_DISABLE_LOGIN_FORM=true
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    ports:
      - 8082:3000
    expose:
      - 3000
    networks:
      - monitoring
  recipies-app:
    hostname: recipies-app
    build:
      context: ./
    ports:
      - 8080:8080
    expose:
      - 8080
    networks:
      - monitoring
volumes:
    prometheus_data: {}
    grafana_data: {}