name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build & Checkout application
    steps:
      - name: Setup Node.js 20
        uses: actions/setup-node@v1
        with:
          node-version: 20.x
    
    name: npm install & lint
    run:
      - npm install
      - npm lint
